CREATE TABLE vin_number (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  vin VARCHAR(50) NOT NULL UNIQUE,
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE'
);

ALTER TABLE car ADD COLUMN vin_id BIGINT UNIQUE;
ALTER TABLE car ADD CONSTRAINT vin_number_fk FOREIGN KEY (vin_id) REFERENCES vin_number(id);
